name: Test Conditional Environment

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - main
  release:
    types: [released]

jobs:
  deploy:
    environment: ${{ github.event_name == 'release' && 'Production' || github.event_name == 'push' && 'Stage' }}
    name: Deploy to ${{ github.event_name == 'release' && 'Production' || github.event_name == 'push' && 'Stage' }}
    if: github.repository == 'MichaelGoberling/test-workflows'
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        node-version: ['18']
        os: [ubuntu-latest]
    steps:
      - name: Deploy
        run: |
          echo "$NAME"
